export const actionTypes = {
    GET_FILM: 'GET_FILM',
    GET_FILM_TRENDING: 'GET_FILM_TRENDING',
    GET_USER: 'GET_USER',
    GET_DETAIL: 'GET_DETAIL',
    GET_VIDEO: 'GET_VIDEO',
    GET_SHOWTIME: 'GET_SHOWTIME',
    SIGN_OUT: 'SIGN_OUT'
}